package co.nicolaspr.analizadorLexico;

/**
 * Clase para dar categoria a los token identificados
 * @author Darwin Bonilla, Nicolas Rios y Santiago Vargas
 *
 */
public enum Categoria {

		IDENTIFICADOR,ENTERO,DECIMALES,OPERADOR_ARITMETICO,OPERADOR_ASIGNACION,OPERADOR_INCREMENTO,
		OPERADOR_DECREMENTO,OPERADOR_RELACIONAL,OPERADOR_LOGICO,LLAVE_DER,LLAVE_IZQ,PARENTESIS_DER,
		PARENTESIS_IZQ,CORCHETE_DER,CORCHETE_IZQ,FIN_SENTENCIA,SEPARADOR,PUNTO,DOS_PUNTOS,COMENTARIO_LINEA,
		COMENTARIO_BLOQUE,CADENA_CARACTERES,CARACTER,PALABRA_RESERVADA,CARACTER_DESCONOCIDO,REAL,ERROR;
}
